
package netum;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Niklas
 */
public class NetumUI extends javax.swing.JFrame {

    /**
     * Creates new form NetumUI
     */
    public NetumUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UusiLaji = new javax.swing.JFrame();
        Lnimi = new javax.swing.JTextField();
        Lkotiplaneetta = new javax.swing.JTextField();
        Lurl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LLisaatietokantaan = new javax.swing.JButton();
        UusiPlaneetta = new javax.swing.JFrame();
        Pnimi = new javax.swing.JTextField();
        Pasukasluku = new javax.swing.JTextField();
        Purl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PLisaatietokantaan1 = new javax.swing.JButton();
        UusiIhminen = new javax.swing.JFrame();
        Inimi = new javax.swing.JTextField();
        Isyntynyt = new javax.swing.JTextField();
        Iurl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Syntymäaika = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ILisaatietokantaan = new javax.swing.JButton();
        PlaneettaLisays = new javax.swing.JButton();
        LajiLisays = new javax.swing.JButton();
        IhminenLisays = new javax.swing.JButton();
        SelaaPlaneetta = new javax.swing.JButton();
        SelaaLaji = new javax.swing.JButton();
        LataaTietokantaan = new javax.swing.JButton();

        jLabel1.setText("Nimi:");

        jLabel2.setText("Kotiplaneetta:");

        jLabel3.setText("URL:");

        LLisaatietokantaan.setText("Lisää Laji tietokantaan");
        LLisaatietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLisaatietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiLajiLayout = new javax.swing.GroupLayout(UusiLaji.getContentPane());
        UusiLaji.getContentPane().setLayout(UusiLajiLayout);
        UusiLajiLayout.setHorizontalGroup(
            UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiLajiLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UusiLajiLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lurl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiLajiLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lkotiplaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiLajiLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lnimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LLisaatietokantaan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        UusiLajiLayout.setVerticalGroup(
            UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiLajiLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lkotiplaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(59, 59, 59)
                .addComponent(LLisaatietokantaan)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel4.setText("Nimi:");

        jLabel5.setText("Asukasluku:");

        jLabel6.setText("URL:");

        PLisaatietokantaan1.setText("Lisää Planeetta tietokantaan");
        PLisaatietokantaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLisaatietokantaan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiPlaneettaLayout = new javax.swing.GroupLayout(UusiPlaneetta.getContentPane());
        UusiPlaneetta.getContentPane().setLayout(UusiPlaneettaLayout);
        UusiPlaneettaLayout.setHorizontalGroup(
            UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Purl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pasukasluku, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pnimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PLisaatietokantaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        UusiPlaneettaLayout.setVerticalGroup(
            UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pnimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pasukasluku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Purl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addComponent(PLisaatietokantaan1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel7.setText("Nimi:");

        Syntymäaika.setText("Syntymäaika:");

        jLabel9.setText("URL:");

        ILisaatietokantaan.setText("Lisää Ihminen tietokantaan");
        ILisaatietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILisaatietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiIhminenLayout = new javax.swing.GroupLayout(UusiIhminen.getContentPane());
        UusiIhminen.getContentPane().setLayout(UusiIhminenLayout);
        UusiIhminenLayout.setHorizontalGroup(
            UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiIhminenLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Iurl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(Syntymäaika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Isyntynyt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ILisaatietokantaan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        UusiIhminenLayout.setVerticalGroup(
            UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiIhminenLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isyntynyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Syntymäaika))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(59, 59, 59)
                .addComponent(ILisaatietokantaan)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlaneettaLisays.setText("Lisää Planeetta");
        PlaneettaLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneettaLisaysActionPerformed(evt);
            }
        });

        LajiLisays.setText("Lisää Laji");
        LajiLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LajiLisaysActionPerformed(evt);
            }
        });

        IhminenLisays.setText("Lisää Ihminen");
        IhminenLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IhminenLisaysActionPerformed(evt);
            }
        });

        SelaaPlaneetta.setText("Selaa Planeettoja");

        SelaaLaji.setText("Selaa Lajeja");

        LataaTietokantaan.setText("Lataa tietokantaan");
        LataaTietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LataaTietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelaaLaji, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(SelaaPlaneetta, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(IhminenLisays, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(LajiLisays, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(PlaneettaLisays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LataaTietokantaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LataaTietokantaan)
                .addGap(43, 43, 43)
                .addComponent(PlaneettaLisays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LajiLisays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IhminenLisays)
                .addGap(67, 67, 67)
                .addComponent(SelaaPlaneetta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelaaLaji)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlaneettaLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneettaLisaysActionPerformed
        UusiPlaneetta.setVisible(true);
        UusiPlaneetta.setSize(400,300);
    }//GEN-LAST:event_PlaneettaLisaysActionPerformed

    private void LajiLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LajiLisaysActionPerformed
        UusiLaji.setVisible(true);
        UusiLaji.setSize(400,300);
    }//GEN-LAST:event_LajiLisaysActionPerformed

    // Ladataan new Netum()-komennolla avataan yhteys tietokantaan ja ladataan
    // JSON-tiedostojen sisältö tietokantaan. 
    private void LataaTietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LataaTietokantaanActionPerformed
        new Netum().lataaJsonit();
    }//GEN-LAST:event_LataaTietokantaanActionPerformed

    private void IhminenLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IhminenLisaysActionPerformed
        UusiIhminen.setVisible(true);
        UusiIhminen.setSize(400,300);
    }//GEN-LAST:event_IhminenLisaysActionPerformed

    private void LLisaatietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLisaatietokantaanActionPerformed
        new Netum().insertSpecies(Lnimi.getText(), Lkotiplaneetta.getText(), Lurl.getText());
    }//GEN-LAST:event_LLisaatietokantaanActionPerformed

    private void PLisaatietokantaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLisaatietokantaan1ActionPerformed
        new Netum().insertPlanet(Pnimi.getText(), Pasukasluku.getText(), Purl.getText());
    }//GEN-LAST:event_PLisaatietokantaan1ActionPerformed

    private void ILisaatietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILisaatietokantaanActionPerformed
        new Netum().insertPeople(Inimi.getText(), Isyntynyt.getText(), Iurl.getText());
    }//GEN-LAST:event_ILisaatietokantaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetumUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ILisaatietokantaan;
    private javax.swing.JButton IhminenLisays;
    private javax.swing.JTextField Inimi;
    private javax.swing.JTextField Isyntynyt;
    private javax.swing.JTextField Iurl;
    private javax.swing.JButton LLisaatietokantaan;
    private javax.swing.JButton LajiLisays;
    private javax.swing.JButton LataaTietokantaan;
    private javax.swing.JTextField Lkotiplaneetta;
    private javax.swing.JTextField Lnimi;
    private javax.swing.JTextField Lurl;
    private javax.swing.JButton PLisaatietokantaan1;
    private javax.swing.JTextField Pasukasluku;
    private javax.swing.JButton PlaneettaLisays;
    private javax.swing.JTextField Pnimi;
    private javax.swing.JTextField Purl;
    private javax.swing.JButton SelaaLaji;
    private javax.swing.JButton SelaaPlaneetta;
    private javax.swing.JLabel Syntymäaika;
    private javax.swing.JFrame UusiIhminen;
    private javax.swing.JFrame UusiLaji;
    private javax.swing.JFrame UusiPlaneetta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
