
package netum;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Niklas
 */
public class NetumUI extends javax.swing.JFrame {

    /**
     * Creates new form NetumUI
     */
    public NetumUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UusiLaji = new javax.swing.JFrame();
        Lnimi = new javax.swing.JTextField();
        Lurl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LLisaatietokantaan = new javax.swing.JButton();
        Lkotiplaneetta = new javax.swing.JComboBox<>();
        UusiPlaneetta = new javax.swing.JFrame();
        Pnimi = new javax.swing.JTextField();
        Pasukasluku = new javax.swing.JTextField();
        Purl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PLisaatietokantaan1 = new javax.swing.JButton();
        UusiIhminen = new javax.swing.JFrame();
        Inimi = new javax.swing.JTextField();
        Isyntynyt = new javax.swing.JTextField();
        Iurl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Syntymäaika = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ILisaatietokantaan = new javax.swing.JButton();
        SivuSelaaPlaneetta = new javax.swing.JFrame();
        ListaPlaneetta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ValitsePlaneetta = new javax.swing.JButton();
        MuokkaaPlaneetta = new javax.swing.JFrame();
        Pid = new javax.swing.JTextField();
        PNimi = new javax.swing.JTextField();
        PAsukas = new javax.swing.JTextField();
        PUrl = new javax.swing.JTextField();
        PaivitaP = new javax.swing.JButton();
        PoistaP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SivuSelaaLajeja = new javax.swing.JFrame();
        ListaLajit = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ValitseLaji = new javax.swing.JButton();
        MuokkaaLajeja = new javax.swing.JFrame();
        Lid = new javax.swing.JTextField();
        LNimi = new javax.swing.JTextField();
        LKotiplaneetta = new javax.swing.JTextField();
        LUrl = new javax.swing.JTextField();
        PaivitaL = new javax.swing.JButton();
        PoistaL = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        PlaneettaLisays = new javax.swing.JButton();
        LajiLisays = new javax.swing.JButton();
        IhminenLisays = new javax.swing.JButton();
        SelaaPlaneetta = new javax.swing.JButton();
        SelaaLaji = new javax.swing.JButton();
        LataaTietokantaan = new javax.swing.JButton();

        jLabel1.setText("Nimi:");

        jLabel2.setText("Kotiplaneetta:");

        jLabel3.setText("URL:");

        LLisaatietokantaan.setText("Lisää Laji tietokantaan");
        LLisaatietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLisaatietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiLajiLayout = new javax.swing.GroupLayout(UusiLaji.getContentPane());
        UusiLaji.getContentPane().setLayout(UusiLajiLayout);
        UusiLajiLayout.setHorizontalGroup(
            UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiLajiLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UusiLajiLayout.createSequentialGroup()
                        .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lurl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkotiplaneetta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lnimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UusiLajiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LLisaatietokantaan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(57, 57, 57))
        );
        UusiLajiLayout.setVerticalGroup(
            UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiLajiLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lnimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Lkotiplaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiLajiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(LLisaatietokantaan)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel4.setText("Nimi:");

        jLabel5.setText("Asukasluku:");

        jLabel6.setText("URL:");

        PLisaatietokantaan1.setText("Lisää Planeetta tietokantaan");
        PLisaatietokantaan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLisaatietokantaan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiPlaneettaLayout = new javax.swing.GroupLayout(UusiPlaneetta.getContentPane());
        UusiPlaneetta.getContentPane().setLayout(UusiPlaneettaLayout);
        UusiPlaneettaLayout.setHorizontalGroup(
            UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Purl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pasukasluku, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pnimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PLisaatietokantaan1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        UusiPlaneettaLayout.setVerticalGroup(
            UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiPlaneettaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pnimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pasukasluku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Purl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(59, 59, 59)
                .addComponent(PLisaatietokantaan1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel7.setText("Nimi:");

        Syntymäaika.setText("Syntymäaika:");

        jLabel9.setText("URL:");

        ILisaatietokantaan.setText("Lisää Ihminen tietokantaan");
        ILisaatietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ILisaatietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UusiIhminenLayout = new javax.swing.GroupLayout(UusiIhminen.getContentPane());
        UusiIhminen.getContentPane().setLayout(UusiIhminenLayout);
        UusiIhminenLayout.setHorizontalGroup(
            UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiIhminenLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Iurl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(Syntymäaika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Isyntynyt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UusiIhminenLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inimi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ILisaatietokantaan, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        UusiIhminenLayout.setVerticalGroup(
            UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UusiIhminenLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Isyntynyt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Syntymäaika))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UusiIhminenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(59, 59, 59)
                .addComponent(ILisaatietokantaan)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jLabel8.setText("Valitse planeetta:");

        ValitsePlaneetta.setText("Valitse");
        ValitsePlaneetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValitsePlaneettaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SivuSelaaPlaneettaLayout = new javax.swing.GroupLayout(SivuSelaaPlaneetta.getContentPane());
        SivuSelaaPlaneetta.getContentPane().setLayout(SivuSelaaPlaneettaLayout);
        SivuSelaaPlaneettaLayout.setHorizontalGroup(
            SivuSelaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SivuSelaaPlaneettaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(SivuSelaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(ListaPlaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SivuSelaaPlaneettaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ValitsePlaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        SivuSelaaPlaneettaLayout.setVerticalGroup(
            SivuSelaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SivuSelaaPlaneettaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(ListaPlaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ValitsePlaneetta)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        Pid.setEditable(false);

        PNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNimiActionPerformed(evt);
            }
        });

        PUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PUrlActionPerformed(evt);
            }
        });

        PaivitaP.setText("Päivitä tiedot");
        PaivitaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaivitaPActionPerformed(evt);
            }
        });

        PoistaP.setText("Poista Planeetta");
        PoistaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoistaPActionPerformed(evt);
            }
        });

        jLabel10.setText("ID");

        jLabel11.setText("Nimi");

        jLabel12.setText("Asukasluku");

        jLabel13.setText("URL");

        javax.swing.GroupLayout MuokkaaPlaneettaLayout = new javax.swing.GroupLayout(MuokkaaPlaneetta.getContentPane());
        MuokkaaPlaneetta.getContentPane().setLayout(MuokkaaPlaneettaLayout);
        MuokkaaPlaneettaLayout.setHorizontalGroup(
            MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuokkaaPlaneettaLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MuokkaaPlaneettaLayout.createSequentialGroup()
                        .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34)))
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuokkaaPlaneettaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PAsukas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MuokkaaPlaneettaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(211, 211, 211))
            .addGroup(MuokkaaPlaneettaLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(PaivitaP)
                .addGap(42, 42, 42)
                .addComponent(PoistaP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MuokkaaPlaneettaLayout.setVerticalGroup(
            MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuokkaaPlaneettaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PAsukas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(49, 49, 49)
                .addGroup(MuokkaaPlaneettaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaivitaP)
                    .addComponent(PoistaP))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jLabel14.setText("Valitse laji:");

        ValitseLaji.setText("Valitse");
        ValitseLaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValitseLajiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SivuSelaaLajejaLayout = new javax.swing.GroupLayout(SivuSelaaLajeja.getContentPane());
        SivuSelaaLajeja.getContentPane().setLayout(SivuSelaaLajejaLayout);
        SivuSelaaLajejaLayout.setHorizontalGroup(
            SivuSelaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SivuSelaaLajejaLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(SivuSelaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(ListaLajit, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SivuSelaaLajejaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ValitseLaji, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        SivuSelaaLajejaLayout.setVerticalGroup(
            SivuSelaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SivuSelaaLajejaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(ListaLajit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ValitseLaji)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        Lid.setEditable(false);

        LNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNimiActionPerformed(evt);
            }
        });

        LUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LUrlActionPerformed(evt);
            }
        });

        PaivitaL.setText("Päivitä tiedot");
        PaivitaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaivitaLActionPerformed(evt);
            }
        });

        PoistaL.setText("Poista Laji");
        PoistaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoistaLActionPerformed(evt);
            }
        });

        jLabel15.setText("ID");

        jLabel16.setText("Nimi");

        jLabel17.setText("Kotiplaneetta");

        jLabel18.setText("URL");

        javax.swing.GroupLayout MuokkaaLajejaLayout = new javax.swing.GroupLayout(MuokkaaLajeja.getContentPane());
        MuokkaaLajeja.getContentPane().setLayout(MuokkaaLajejaLayout);
        MuokkaaLajejaLayout.setHorizontalGroup(
            MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuokkaaLajejaLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MuokkaaLajejaLayout.createSequentialGroup()
                        .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addGap(34, 34, 34)))
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MuokkaaLajejaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LKotiplaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MuokkaaLajejaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(211, 211, 211))
            .addGroup(MuokkaaLajejaLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(PaivitaL)
                .addGap(42, 42, 42)
                .addComponent(PoistaL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MuokkaaLajejaLayout.setVerticalGroup(
            MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MuokkaaLajejaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(13, 13, 13)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKotiplaneetta, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(49, 49, 49)
                .addGroup(MuokkaaLajejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaivitaL)
                    .addComponent(PoistaL))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlaneettaLisays.setText("Lisää Planeetta");
        PlaneettaLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneettaLisaysActionPerformed(evt);
            }
        });

        LajiLisays.setText("Lisää Laji");
        LajiLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LajiLisaysActionPerformed(evt);
            }
        });

        IhminenLisays.setText("Lisää Ihminen");
        IhminenLisays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IhminenLisaysActionPerformed(evt);
            }
        });

        SelaaPlaneetta.setText("Selaa Planeettoja");
        SelaaPlaneetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelaaPlaneettaActionPerformed(evt);
            }
        });

        SelaaLaji.setText("Selaa Lajeja");
        SelaaLaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelaaLajiActionPerformed(evt);
            }
        });

        LataaTietokantaan.setText("Lataa tietokantaan");
        LataaTietokantaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LataaTietokantaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelaaLaji, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(SelaaPlaneetta, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(IhminenLisays, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(LajiLisays, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(PlaneettaLisays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LataaTietokantaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LataaTietokantaan)
                .addGap(43, 43, 43)
                .addComponent(PlaneettaLisays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LajiLisays)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IhminenLisays)
                .addGap(67, 67, 67)
                .addComponent(SelaaPlaneetta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelaaLaji)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    "Lisää Planeetta" - painikeen painalluksen jälkeen avataan UusiPlaneetta-ikkuna,
    jossa käyttäjä voi lisätä uusia planeettoja. 
    */
    private void PlaneettaLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaneettaLisaysActionPerformed
        UusiPlaneetta.setVisible(true);
        UusiPlaneetta.setSize(400,300);
    }//GEN-LAST:event_PlaneettaLisaysActionPerformed

    /*
    "Lisää Laji" - painikeen painalluksen jälkeen avataan UusiLaji-ikkuna,
    jossa käyttäjä voi lisätä uusia Lajeja. UusiLaji-ikkunalla olevasta
    Comboboxista (Lkotiplaneetta) tyhjennetää sisältö ja täytetään uusilla
    tietokannasta löydetyistä planeetan nimillä. Netum-luokasta kutsutaan
    getPlanetNames-funktioa, joka palauttaa taulukkona kaikki planeetta-taulun
    planeettojen nimet, jotka for-silmukassa lisätään Comboboxin itemeiksi. 
    */
    private void LajiLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LajiLisaysActionPerformed
        UusiLaji.setVisible(true);
        UusiLaji.setSize(400,300);
        Lkotiplaneetta.removeAllItems();
        String [] nimet = new Netum().getPlanetNames();
        for (int i = 0; i < nimet.length; i++) {
            if (nimet[i] != null) {
                Lkotiplaneetta.addItem(nimet[i]);
            }
        }
    }//GEN-LAST:event_LajiLisaysActionPerformed

    // Ladataan new Netum()-komennolla avataan yhteys tietokantaan ja ladataan
    // JSON-tiedostojen sisältö tietokantaan. 
    private void LataaTietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LataaTietokantaanActionPerformed
        new Netum().lataaJsonit();
    }//GEN-LAST:event_LataaTietokantaanActionPerformed

     /*
    "Lisää Ihminen" - painikeen painalluksen jälkeen avataan UusiIhminen-ikkuna,
    jossa käyttäjä voi lisätä uusia Ihmisiä tietokantaan. 
    */
    private void IhminenLisaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IhminenLisaysActionPerformed
        UusiIhminen.setVisible(true);
        UusiIhminen.setSize(400,300);
    }//GEN-LAST:event_IhminenLisaysActionPerformed

     /*
    "Lisää Tietokantaan" (laji) - painikeen painalluksen jälkeen kutsutaan Netum-
    luokan funktioa insertSpecies. Funktiolle annetaan parametreina käyttäjän 
    käyttöliittymään syöttämät tiedot eli nimi, kotiplaneetta ja lajin url.
    Netum-luokan funktio tallentaa tiedot tietokantaan. 
    */
    private void LLisaatietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLisaatietokantaanActionPerformed
        new Netum().insertSpecies(Lnimi.getText(), Lkotiplaneetta.getSelectedItem().toString(), Lurl.getText());
    }//GEN-LAST:event_LLisaatietokantaanActionPerformed
 
    /*
    "Lisää Tietokantaan" (planeetta) - painikeen painalluksen jälkeen kutsutaan Netum-
    luokan funktioa insertPlanet. Funktiolle annetaan parametreina käyttäjän 
    käyttöliittymään syöttämät tiedot eli nimi, asukasluku ja lajin url.
    Netum-luokan funktio tallentaa tiedot tietokantaan. 
    */
    private void PLisaatietokantaan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLisaatietokantaan1ActionPerformed
        new Netum().insertPlanet(Pnimi.getText(), Pasukasluku.getText(), Purl.getText());
    }//GEN-LAST:event_PLisaatietokantaan1ActionPerformed

    /*
    "Lisää Tietokantaan" (ihminen) - painikeen painalluksen jälkeen kutsutaan Netum-
    luokan funktioa insertPeople. Funktiolle annetaan parametreina käyttäjän 
    käyttöliittymään syöttämät tiedot eli nimi, syntymäaika ja url.
    Netum-luokan funktio tallentaa tiedot tietokantaan. 
    */
    private void ILisaatietokantaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ILisaatietokantaanActionPerformed
        new Netum().insertPeople(Inimi.getText(), Isyntynyt.getText(), Iurl.getText());
    }//GEN-LAST:event_ILisaatietokantaanActionPerformed

    
    /*
    Käyttöliittymän etusivun "Selaa Planeettoja" painiketta painettaessa 
    poistetaan ListaPlaneetta comboboxista itemit ja täytetään combobox 
    uusilla (mahdollisesti päivitetyillä) planeettojen nimillä. Tämä tapahtuu
    kutsumalla Netum-luokan getPlanetNames-funktioa, joka palauttaa 
    tietokannasta löytyvien planeettojen nimet taulukossa, jotka käsitellään
    for-silmukassa lisäten ne comboboxin(ListaPlaneetta) itemeiksi. Sen jälkeen
    aseteteaan Planeettojen selaussivu näkyväksi. 
    */
    private void SelaaPlaneettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelaaPlaneettaActionPerformed
        ListaPlaneetta.removeAllItems();
        String [] nimet = new Netum().getPlanetNames();
        for (int i = 0; i < nimet.length; i++) {
            if (nimet[i] != null) {
                ListaPlaneetta.addItem(nimet[i]);
            }
        }
        SivuSelaaPlaneetta.setVisible(true);
        SivuSelaaPlaneetta.setSize(400,300);
    }//GEN-LAST:event_SelaaPlaneettaActionPerformed

    /*
    Planeetan selaussivulta löytyy combobox, josta käyttäjä voi valita
    haluamansa planeetan tarkasteluun. Kun käyttäjä on valinnut comboboxista 
    planeetan ja painaa "valitse planeetta" painiketta. Tapahtuu alla oleva
    funktio. Funktiossa lähetetään Netum-luokan getPlanetInfo-funktiolle parametrina 
    planeetan nimi, joka palauttaa taulukkona kaikki tämän planeetan tiedot. 
    Funktio asettaa taulukosta tiedot MuokkaaPlaneetta-sivun kenttiin jatko-
    käsittelyä varten ja asettaa sivun näkyväksi. 
    */
    private void ValitsePlaneettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValitsePlaneettaActionPerformed
        String [] tiedot = new Netum().getPlanetInfo(ListaPlaneetta.getSelectedItem().toString());
        Pid.setText(tiedot[0]);
        PNimi.setText(tiedot[1]);
        PAsukas.setText(tiedot[2]);
        PUrl.setText(tiedot[3]);
        MuokkaaPlaneetta.setVisible(true);
        MuokkaaPlaneetta.setSize(600,600);
        
    }//GEN-LAST:event_ValitsePlaneettaActionPerformed

    private void PNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PNimiActionPerformed

    private void PUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PUrlActionPerformed

    /*
    Muokkaa Planeetta sivun "Paivita Planeetta" painikkeen painalluksen jälkeen
    kutsutaan Netum-luokan updatePlanetInfo-funktioa, joka saa parametrina
    tekstikentistä löytyvät id:n(ei voi muokata), nimen, asukasluvun ja urlin.
    Funktio muokkaa tietokannan tietoja annettujen parametrien mukaisiksi.
    */
    private void PaivitaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaivitaPActionPerformed
        new Netum().updatePlanetInfo(Pid.getText(), PNimi.getText(), PAsukas.getText(), PUrl.getText());
    }//GEN-LAST:event_PaivitaPActionPerformed
  
    /*
    Muokkaa Planeetta sivun "Poista Planeetta" painikkeen painalluksen jälkeen
    kutsutaan Netum-luokan deletePlanet-funktioa, joka saa parametrina
    tekstikentistä löytyvät id:n. Tämän avulla funktio poistaa valitun 
    planeetan tietokannasta.
    */
    private void PoistaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoistaPActionPerformed
        new Netum().deletePlanetInfo(Pid.getText());
    }//GEN-LAST:event_PoistaPActionPerformed

    
    /*
    Käyttöliittymän etusivun "Selaa Lajeja" painiketta painettaessa 
    poistetaan ListaLajit comboboxista itemit ja täytetään combobox 
    uusilla (mahdollisesti päivitetyillä) lajien nimillä. Tämä tapahtuu
    kutsumalla Netum-luokan getSpeciesNames-funktioa, joka palauttaa 
    tietokannasta löytyvien lajien nimet taulukossa, jotka käsitellään
    for-silmukassa lisäten ne comboboxin(ListaLajit) itemeiksi. Sen jälkeen
    aseteteaan Lajien selaussivu näkyväksi. 
    */
    private void SelaaLajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelaaLajiActionPerformed
        ListaLajit.removeAllItems();
        String [] nimet = new Netum().getSpeciesNames();
        for (int i = 0; i < nimet.length; i++) {
            if (nimet[i] != null) {
                ListaLajit.addItem(nimet[i]);
            }
        }
        SivuSelaaLajeja.setVisible(true);
        SivuSelaaLajeja.setSize(400,300);
    }//GEN-LAST:event_SelaaLajiActionPerformed

     /*
    Lajin selaussivulta löytyy combobox, josta käyttäjä voi valita
    haluamansa lajin tarkasteluun. Kun käyttäjä on valinnut comboboxista 
    lajin ja painaa "valitse laji" painiketta. Tapahtuu alla oleva
    funktio. Funktiossa lähetetään Netum-luokan getSpeciesInfo-funktiolle parametrina 
    lajin nimi, joka palauttaa taulukkona kaikki tämän lajin tiedot. 
    Funktio asettaa taulukosta tiedot MuokkaaLajeja-sivun kenttiin jatko-
    käsittelyä varten ja asettaa sivun näkyväksi. 
    */
    private void ValitseLajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValitseLajiActionPerformed
        String [] tiedot = new Netum().getSpeciesInfo(ListaLajit.getSelectedItem().toString());
        Lid.setText(tiedot[0]);
        LNimi.setText(tiedot[1]);
        LKotiplaneetta.setText(tiedot[2]);
        LUrl.setText(tiedot[3]);
        MuokkaaLajeja.setVisible(true);
        MuokkaaLajeja.setSize(600,600);
    }//GEN-LAST:event_ValitseLajiActionPerformed

    private void LNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNimiActionPerformed

    private void LUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LUrlActionPerformed

    /*
    Muokkaa Lajeja sivun "Paivita Laji" painikkeen painalluksen jälkeen
    kutsutaan Netum-luokan updateSpeciesInfo-funktioa, joka saa parametrina
    tekstikentistä löytyvät id:n(ei voi muokata), nimen, kotiplaneetan ja urlin.
    Funktio muokkaa tietokannan tietoja annettujen parametrien mukaisiksi.
    */
    private void PaivitaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaivitaLActionPerformed
        new Netum().updateSpeciesInfo(Lid.getText(), LNimi.getText(), LKotiplaneetta.getText(), LUrl.getText());
    }//GEN-LAST:event_PaivitaLActionPerformed

    /*
    Muokkaa Lajeja sivun "Poista Laji" painikkeen painalluksen jälkeen
    kutsutaan Netum-luokan deleteSpeciesInfo-funktioa, joka saa parametrina
    tekstikentistä löytyvät id:n. Tämän avulla funktio poistaa valitun 
    lajin tietokannasta.
    */
    private void PoistaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoistaLActionPerformed
        new Netum().deleteSpeciesInfo(Lid.getText());
    }//GEN-LAST:event_PoistaLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetumUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetumUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ILisaatietokantaan;
    private javax.swing.JButton IhminenLisays;
    private javax.swing.JTextField Inimi;
    private javax.swing.JTextField Isyntynyt;
    private javax.swing.JTextField Iurl;
    private javax.swing.JTextField LKotiplaneetta;
    private javax.swing.JButton LLisaatietokantaan;
    private javax.swing.JTextField LNimi;
    private javax.swing.JTextField LUrl;
    private javax.swing.JButton LajiLisays;
    private javax.swing.JButton LataaTietokantaan;
    private javax.swing.JTextField Lid;
    private javax.swing.JComboBox<String> ListaLajit;
    private javax.swing.JComboBox<String> ListaPlaneetta;
    private javax.swing.JComboBox<String> Lkotiplaneetta;
    private javax.swing.JTextField Lnimi;
    private javax.swing.JTextField Lurl;
    private javax.swing.JFrame MuokkaaLajeja;
    private javax.swing.JFrame MuokkaaPlaneetta;
    private javax.swing.JTextField PAsukas;
    private javax.swing.JButton PLisaatietokantaan1;
    private javax.swing.JTextField PNimi;
    private javax.swing.JTextField PUrl;
    private javax.swing.JButton PaivitaL;
    private javax.swing.JButton PaivitaP;
    private javax.swing.JTextField Pasukasluku;
    private javax.swing.JTextField Pid;
    private javax.swing.JButton PlaneettaLisays;
    private javax.swing.JTextField Pnimi;
    private javax.swing.JButton PoistaL;
    private javax.swing.JButton PoistaP;
    private javax.swing.JTextField Purl;
    private javax.swing.JButton SelaaLaji;
    private javax.swing.JButton SelaaPlaneetta;
    private javax.swing.JFrame SivuSelaaLajeja;
    private javax.swing.JFrame SivuSelaaPlaneetta;
    private javax.swing.JLabel Syntymäaika;
    private javax.swing.JFrame UusiIhminen;
    private javax.swing.JFrame UusiLaji;
    private javax.swing.JFrame UusiPlaneetta;
    private javax.swing.JButton ValitseLaji;
    private javax.swing.JButton ValitsePlaneetta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
